version: '3'
services:
    mysql56:
        image: mysql:5.6
        container_name: mysql56-container
        ports:
          - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: livrariadb